"""fix users table name

Revision ID: 2301337e5f35
Revises: 54e86d34c5a7
Create Date: 2026-02-13 07:34:22.152134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2301337e5f35'
down_revision: Union[str, Sequence[str], None] = '54e86d34c5a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('unit_price', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('cart_items', sa.Column('currency', sa.String(length=10), nullable=False))
    op.drop_constraint(op.f('FK__cart_item__cart___56E8E7AB'), 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'carts', ['cart_id'], ['id'], ondelete='CASCADE')
    op.drop_column('cart_items', 'added_price')
    op.create_foreign_key(None, 'carts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_Users_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phoneNumber'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_Users_id'), 'users', ['id'], unique=False)
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.add_column('cart_items', sa.Column('added_price', sa.DECIMAL(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key(op.f('FK__cart_item__cart___56E8E7AB'), 'cart_items', 'carts', ['cart_id'], ['id'])
    op.drop_column('cart_items', 'currency')
    op.drop_column('cart_items', 'unit_price')
    # ### end Alembic commands ###
